apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: microservicios
  name: microservicios
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservicios
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: microservicios
    spec:
      containers:
      - image: tomasrm/eureka:latest
        name: eureka
        resources: {}
status: {}
