apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: microservicios
  name: microservicios
spec:
  ports:
  - name: 8761-8761
    port: 8761
    protocol: TCP
    targetPort: 8761
  selector:
    app: microservicios
  type: ClusterIP
status:
  loadBalancer: {}
